export const SET_CATEGORIES = 'SET_CATEGORIES';

export const REMOVE_VISIBLE_CATEGORY = 'REMOVE_VISIBLE_CATEGORY';
export const ADD_VISIBLE_CATEGORY = 'ADD_VISIBLE_CATEGORY';

export const SET_LOCATION = 'SET_LOCATION';

export const GETTING_CRIMES = 'GETTING_CRIMES';
export const GOT_CRIMES = 'GOT_CRIMES';