export const SET_CATEGORIES = 'SET_CATEGORIES';

export const REMOVE_VISIBLE_CATEGORY = 'REMOVE_VISIBLE_CATEGORY';
export const ADD_VISIBLE_CATEGORY = 'ADD_VISIBLE_CATEGORY';

export const SET_LOCATION = 'SET_LOCATION';

export const GETTING_CRIMES = 'GETTING_CRIMES';
export const GOT_CRIMES = 'GOT_CRIMES';

export const SET_POLICE_API_LAST_UPDATED = 'SET_POLICE_API_LAST_UPDATED';

export const SET_SEARCH_INPUT = 'SET_SEARCH_INPUT';
export const SET_SEARCH_SUGGESTIONS = 'SET_SEARCH_SUGGESTIONS';

export const SET_SELECTED_MONTH_YEAR = 'SET_SELECTED_MONTH_YEAR';